### ISSUE TITLE
Tool Usage Tips

### ISSUE THREAD

**Issue by cihanmehmet** [AlephNullSK/dnsgen#1]
It can be used for DNS resolution as follows.
### Usage 1(fping)
```
cat domains.txt | dnsgen - |fping|grep "alive"|cut -d " " -f1>resolvers.txt
```
### Usage 2(httprobe )
```
cat domains.txt | dnsgen - |httprobe|cut -d "/" -f3|sort -u |tee resolvers.txt
```
<img width="645" alt="resolver" src="https://user-images.githubusercontent.com/7144304/65857924-87c0a300-e36d-11e9-91d8-59d3f5ff50c5.png">

**Comment by ghost** [comment]
is there a way to output this to a file? i did not see a way to only to print out on my terminal?

**Comment by PatrikHudak** [comment]
@soupnatzi You can redirect the STDOUT to any file you want

`dnsgen domains.txt > output.txt`

...or if you want to pipe it further and still save it then `dnsgen domains.txt | tee output.txt | nextcommand`

**Comment by PatrikHudak** [comment]
@cihanmehmet These definitely work as well, the `dnsgen` is used only for generation, resolving part if left up to user.

**Comment by ghost** [comment]
@PatrikHudak got it thanks Patrick great tool and this is giving way less false positives then altdns.
