### ISSUE TITLE
Base Subdomains are not included.

### ISSUE THREAD

**Issue by vipinbihari** [AlephNullSK/dnsgen#6]
Hi,
when I run all found subdomain for alteration through dnsgen then some of the base domain are not there in output file.

Suppose I have subdomain named xyx.example.com and many more subdomins of example.com.
When a file containing all these sort of subdomais are given to dnsgen then the altered domains does not include xyx.example.com in the output file.
NOTE: It gives its childrens. (abc.xyx.example.com). But not xyx.example.com. Hence when ran through massdns it affects its results.

**Comment by ghost** [comment]
Yes because its expected, that those "base subdomains" are known to be alive. Only alterations of it are found in the output and that is its intended behaviour.
